Search User implementation
scorelab/OpenMF pull request #293
Opened 2022-08-03 21:23 UTC by PrerakMathur20

# Description

Added Search User functionality to the **Search User** page, with multiple new functionalities, such as -
* Download `.csv` list of all users
* Print `.pdf` of all users
* **Show** or **Hide** Columns
* Conditional Column Filters

Fixes #281 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

All fields were checked and searched for as per the search query.

Also, include screenshots for the verification and reviewing purpose.
<img width="1669" alt="Screenshot 2022-07-25 at 7 31 53 AM" src="https://user-images.githubusercontent.com/76054330/180678856-eaed952a-931d-482f-8875-9becece729d8.png">

### Demo
https://user-images.githubusercontent.com/76054330/180678913-087d41d1-2d92-4203-b568-65ee5fefcf7b.mov

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works **(N/A)**
- [ ] New and existing unit tests pass locally with my changes **(N/A)**
- [ ] Any dependent changes have been merged and published in downstream modules **(N/A)**

2022-08-13 05:33 UTC, swapnalshahil requested changes

2022-08-13 05:33 UTC, swapnalshahil commented on React-frontend/src/components/Admin/SearchUserModel.js
> +                 console.log("data, type, row", data, type, row);
Comment this line (console.log)!

2022-08-13 05:33 UTC, swapnalshahil commented on React-frontend/src/components/Admin/SearchUserModel.js
> +         console.log(newRows);
This one also!

2022-08-13 21:18 UTC, PrerakMathur20 commented
Since those lines were unnecessary and useless as comments, so I removed them.

2022-08-14 06:35 UTC, swapnalshahil approved these changes
LGTM!

2022-08-14 06:35 UTC, merged